// Google login migrated to native Supabase OAuth.
// Lovable auth disabled - remove if not used elsewhere.
// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft", opts?: SignInOptions) => {
      throw new Error('Lovable OAuth disabled - use native Supabase signInWithOAuth instead');
    },
  },
};
